dist: trusty
sudo: yes
language: minimal

env:
  global:
    - LXC_DIST=alpine
    - LXC_RELEASE=edge

before_install:
  - sh lxc.sh
  - shopt -s expand_aliases && alias run='sudo lxc-attach -n travis -- '

script:
  - set -eo pipefail
  - run ping github.com -c 2
  - run true && echo "a"