dist: trusty
sudo: yes
language: minimal

env:
  global:
    - LXC_DIST=alpine
    - LXC_RELEASE=edge

before_install:
  - sh lxc.sh
  - run() { sudo lxc-attach -n travis -- $@ ; }

script:
  - set -eo pipefail
  - run ping github.com -c 2